---
# tasks file for tomrole
- name: install tomcat
  apt:
    name: tomcat7
    state: present
- name: copy my tom config
  template:
     src: tomconfig.j2
     dest: /etc/default/tomcat7    
  notify: restarttomcat

- name: install admin packages       
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - tomcat7-docs
    - tomcat7-admin
    - tomcat7-examples

- name: copy tomcatuser file interface
  template:
    src: tomusers.j2
    dest:  /etc/tomcat7/tomcat-users.xml
  notify: restarttomcat